export { booksTable } from './booksTable'
export { authorsTable } from './authorsTable'
export { usersTable } from './usersTable'
export { newsTable } from './newsTable'
export { ordersTable } from './ordersTable'
