import { DB_REPO } from '@/constants'

export const env = {
  serverBaseUrl: Bun.env.SERVER_BASE_URL ?? 'http://localhost:5000',
  port: Bun.env.PORT ?? '5000',
  cookieSecret: Bun.env.COOKIE_SECRET,
  cookieMaxAge: Bun.env.COOKIE_MAX_AGE ?? '1209600',
  clientBaseUrl: Bun.env.CLIENT_BASE_URL,
  dbRepo: Bun.env.DB_REPO === DB_REPO.MONGO ? DB_REPO.MONGO : DB_REPO.SQLITE,
  dbSqliteFile: Bun.env.DB_SQLITE_FILE ?? 'data/db.sqlite',
  dbMongoUrl:
    Bun.env.DB_MONGO_URL ?? 'mongodb://host.docker.internal:27017/bookshop',
  adminEmail: Bun.env.ADMIN_EMAIL,
  adminPassword: Bun.env.ADMIN_PASSWORD,
  mailerUser: Bun.env.MAILER_USER,
  mailerPass: Bun.env.MAILER_PASS,
  jwtAccessSecret: Bun.env.ACCESS_TOKEN_SECRET,
  jwtRefreshSecret: Bun.env.REFRESH_TOKEN_SECRET,
  jwtAccessExpiration: Bun.env.ACCESS_TOKEN_EXPIRATION ?? '900',
  jwtRefreshExpiration: Bun.env.REFRESH_TOKEN_EXPIRATION ?? '1209600',
  ngrokAuthToken: Bun.env.NGROK_AUTHTOKEN,
  ngrokDomain: Bun.env.NGROK_DOMAIN,
  stripeSecret: Bun.env.STRIPE_SECRET,
  awsAccessKeyId: Bun.env.AWS_ACCESS_KEY_ID,
  awsSecretAccessKey: Bun.env.AWS_SECRET_ACCESS_KEY,
  awsRegion: Bun.env.AWS_REGION,
  awsBucket: Bun.env.AWS_BUCKET,
  logtailServerSourceToken: Bun.env.LOGTAIL_SERVER_SOURCE_TOKEN,
  logtailServerIngestingHost: Bun.env.LOGTAIL_SERVER_INGESTING_HOST,
  logtailWorkerSourceToken: Bun.env.LOGTAIL_WORKER_SOURCE_TOKEN,
  logtailWorkerIngestingHost: Bun.env.LOGTAIL_WORKER_INGESTING_HOST,
  redisUrl: Bun.env.REDIS_URL,
}
