export * as authorsDB from './authors.repo'
export * as booksDB from './books.repo'
export * as newsDB from './news.repo'
export * as ordersDB from './orders.repo'
export * as usersDB from './users.repo'
